name: build_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  # PIPELINE CONFIGURATION
  minimumCoverage: 0.85
  pythonVersion: '3.7'

  # NOT FOR CONFIGURATION
  # Go installation path, we want to use go 1.13
  GOROOT: '/usr/local/go1.13'
  # Go binaries path
  GOBIN:  '$(system.defaultWorkingDirectory)/gobin'

trigger:
  batch: true
  branches:
    include:
      - dev
    exclude:
      - build_*
      - v*
      - master

pr:
  - dev

jobs:

- job: 'CI_CD'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  # Setup python environment
  - template: zdevelop/azure_templates/setup_git.yml
  # Setup python environment
  - template: zdevelop/azure_templates/setup_python.yml
  # Setup go environment
  - template: zdevelop/azure_templates/setup_go.yml

  # Run job
  - script: revive -config revive.toml ./...
    displayName: 'Lint'

  - script: |
      mkdir ./reports
      set -o pipefail
      go test \
      -v \
      -covermode=count \
      -coverpkg=./... \
      -coverprofile=coverage.out \
      ./... \
      -minimum-coverage=$(minimumCoverage) \
      | tee ./reports/testResults.txt
    displayName: 'Run Tests'

  - script: cat ./reports/testResults.txt | go-junit-report > ./reports/tests_junit.xml
    condition: succeededOrFailed()
    displayName: 'Convert test report to junit'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: /reports/tests_junit.xml
      failTaskOnFailedTests: true

