name: build_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  # PIPELINE CONFIGURATION
  minimumCoverage: 0.85
  pythonVersion: '3.7'
  goVersionLink: https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz

  # NOT FOR CONFIGURATION
  # Go installation path, we want to use go 1.13
  GOROOT: '$(Agent.BuildDirectory)/go'
  # Go binaries path
  GOBIN:  '$(Agent.BuildDirectory)/gobin'

trigger:
  batch: true
  # We are going to only be doing builds for the 'dev' branch. Master will be updated
  # from dev on successful builds rather than being updated directly.
  branches:
    include:
      - dev
    exclude:
      - build_*
      - v*
      - master

pr:
  - dev

jobs:

- job: 'CI_CD'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  # Setup python environment
  - template: zdevelop/azure_templates/setup_git.yml
  # Setup python environment
  - template: zdevelop/azure_templates/setup_python.yml
  # Setup go environment
  - template: zdevelop/azure_templates/setup_go.yml

  # Run job
  - script: revive -config revive.toml ./...
    displayName: 'Lint'

  # Release the module on github.
  - template: zdevelop/azure_templates/go_run_tests.yml

  # Get the release version
  - script: python3 zdevelop/azure_scripts/get_release_version.py
    displayName: 'get release version'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

  - script: 'wget --help'
    displayName: 'Debug wget help'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

  # Build API documentation. We just need to build the source static html files here
  # and readthedocs will take care of the rest.
  - script: docmodule-go
    displayName: 'Build docs'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

  # Release the module on github.
  - template: zdevelop/azure_templates/go_release_module.yml
