name: build_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - dev
    exclude:
      - build_*
      - v*
      - master

pr:
  - dev

jobs:

- job: 'CI/CD'

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7'
            architecture: 'x64'

      - script: go get -u golang.org/x/tools/cmd/godoc
        displayName: 'Download GoDoc'

      - script: go get -u github.com/illuscio-dev/docmodule-go
        displayName: 'Download GoModule'

      - script: revive -config revive.toml ./...
        displayNamee: 'Lint'
