name: build_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  # PIPELINE CONFIGURATION
  minimumCoverage: 0.85
  pythonVersion: '3.7'

  # NOT FOR CONFIGURATION
  # Go binaries path
  GOBIN:  '$(GOPATH)/bin'
  # Go installation path, we want to use go 1.13
  GOROOT: '/usr/local/go1.13'
  # Go workspace path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  # Path to the module's code
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

trigger:
  batch: true
  branches:
    include:
      - dev
    exclude:
      - build_*
      - v*
      - master

pr:
  - dev

jobs:

- job: 'CI_CD'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:

  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Set up the Go workspace'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      architecture: 'x64'

  # Install SSH key
  # Install an SSH key prior to a build or deployment
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDrTwn50yyQO2HpBZKvTU5hPKGPEa/XUfOpaUGFKInrFhj5zhqA/y3fAPHtp8r3+GJ/Wapu1/iS7mALApK3QbF41t6vL3sLM+k8qBPLckNsEmaLcb+Q+KOGGjbdODZ8M6PR+2PG+ckoPfRi5D0Mdu669AUqJvkmKWbHPZAHi8SS4ibQjTivoq8fPJmHJyuoCWBSaWGFctdf/JegrBTtWE1GrY6Mnf3X/BU5CYbaBSockgyzy64Pu1KjXzWpInXgnb+WhKcY7icihX/TosDJHHACKpS/cAYQ3jH/WcIkXtqz71RZMtoV3A3mfFgsq9yPpde25jRVjBM7KxpmU79iXZ8q6JA2jDJIcHFHXhNQytqSHo10KAb8cWuM2uFoMLNk9UNM3Gyd1KBFzicqbo/yoXYoY7fZhBGjnhqI2XqG3qNQsz7njvUcFltYpsHGtCDeBL0AiLjmiaWJ01/Nl2qvTWKguzVDFe1FHCOKAPaNeTynnCeygNS4njReeBQhredKq2am3x2RotIkwe8V8HGfWY15sSrHeBlTI68V+rHTPegOTJZaf6ETiTaO3vf4+o3d+It4Y829dUcOFCfO40Ojzej5Ep1MbS7oH3NxtErkuwQVJZwhA4tn6pMPn0l+PsX7M2dZvDtPE/YUERU3lpA5BqLC+CJPJjsz6u9f6IHXtifeYQ== cicd@illuscio.com
      sshPassphrase: hVtoa8xbRv4-bVfMUsTr
      sshKeySecureFile: ci_cd.private

  - script: |
      git config --global --add url."ssh://git@github.com/".insteadOf "https://github.com/"
    displayName: 'Registering git repo access.'

  - script: go version
    displayName: 'Print go version'

  - script: go env
    displayName: 'Print go env'

  - script: |
      go get -u github.com/illuscio-dev/docmodule-go
      go get -u golang.org/x/tools/cmd/godoc
      go get -u github.com/mgechev/revive
      go get -u github.com/jstemmer/go-junit-report
    displayName: 'Go get CLI tools'
    workingDirectory: /home

  - script: go get -v -t -d ./...
    workingDirectory: '$(modulePath)'
    displayName: 'Go get dependencies'

  - script: revive -config revive.toml ./...
    workingDirectory: '$(modulePath)'
    displayName: 'Lint'

  - script: |
      mkdir ./reports
      set -o pipefail
      go test \
      -v \
      -covermode=count \
      -coverpkg=./... \
      -coverprofile=coverage.out \
      ./... \
      -minimum-coverage=$(minimumCoverage) \
      | tee ./reports/testResults.txt
    workingDirectory: '$(modulePath)'
    displayName: 'Run Tests'

  - script: cat ./reports/testResults.txt | go-junit-report > ./reports/tests_junit.xml
    condition: succeededOrFailed()
    workingDirectory: '$(modulePath)'
    displayName: 'Convert test report to junit'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: $(modulePath)/reports/tests_junit.xml
      failTaskOnFailedTests: true

  - task: PythonScript@0
    displayName: 'check for version conflict'
    inputs:
      scriptSource: filePath
      scriptPath: '$(modulePath)/zdevelop/azure_scripts/get_release_version.py'
      failOnStderr: true

  - script: echo $(RELEASE_VERSION)
    displayName: 'debug release version'