name: build_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  # PIPELINE CONFIGURATION
  minimumCoverage: 0.85
  pythonVersion: '3.7'

  # NOT FOR CONFIGURATION
  # Go installation path, we want to use go 1.13
  GOROOT: '/usr/local/go1.13'
  # Go binaries path
  GOBIN:  '$(system.defaultWorkingDirectory)/gobin'

trigger:
  batch: true
  # We are going to only be doing builds for the 'dev' branch. Master will be updated
  # from dev on successful builds rather than being updated directly.
  branches:
    include:
      - dev
    exclude:
      - build_*
      - v*
      - master

pr:
  - dev

jobs:

- job: 'CI_CD'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  # Setup python environment
  - template: zdevelop/azure_templates/setup_git.yml
  # Setup python environment
  - template: zdevelop/azure_templates/setup_python.yml
  # Setup go environment
  - template: zdevelop/azure_templates/setup_go.yml

  # Run job
  - script: revive -config revive.toml ./...
    displayName: 'Lint'

  # Release the module on github.
  - template: zdevelop/azure_templates/go_run_tests.yml

  # Release the module on github.
  - template: zdevelop/azure_templates/go_release_module.yml
